apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  # It is a good practice to declare resource requests and limits for both memory and cpu for each container.
  containers:
    - image: flqktm123/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP